### DISCUSSION TITLE
Deploying 5GCORE, ZMQ GNB and ZMQ 5G UE on separate machines

### DISCUSSION THREAD

**Discussion by ahmadhassandebugs** [herlesupreeth/docker_open5gs#352] [General]
I am working on a setup where I have three machines.

- M1 (Open5GS)
- M2 (ZMQ GNB)
- M3 (ZMQ 5G UE)

I have followed the readme file but I am unable to connect ZMQ UE with the ZMQ GNB.

Here are the environment files for each machine.

M1
```
# Set proper timezone to sync times between docker host and containers
#TZ=Europe/Berlin

MCC=001
MNC=01

TEST_NETWORK=172.22.0.0/24
DOCKER_HOST_IP=10.182.50.57

# MONGODB
MONGO_IP=172.22.0.2

# HSS - open5gs
HSS_IP=172.22.0.3

# PCRF
PCRF_IP=172.22.0.4
PCRF_BIND_PORT=3873

# SGW
SGWC_IP=172.22.0.5
SGWU_IP=172.22.0.6
SGWU_ADVERTISE_IP=172.22.0.6

# SMF
SMF_IP=172.22.0.7
SMF_DNS1=8.8.8.8
SMF_DNS2=8.8.4.4

# UPF
UPF_IP=172.22.0.8
UPF_ADVERTISE_IP=10.182.50.57

# MME
MME_IP=172.22.0.9

# AMF
AMF_IP=172.22.0.10

# AUSF
AUSF_IP=172.22.0.11

# NRF
NRF_IP=172.22.0.12

# UDM
UDM_IP=172.22.0.13

# UDR
UDR_IP=172.22.0.14

# IMS DNS
DNS_IP=172.22.0.15

# RTPENGINE
RTPENGINE_IP=172.22.0.16

# MYSQL
MYSQL_IP=172.22.0.17

# PYHSS
PYHSS_IP=172.22.0.18
PYHSS_BIND_PORT=3875

# ICSCF
ICSCF_IP=172.22.0.19
ICSCF_BIND_PORT=3869

# SCSCF
SCSCF_IP=172.22.0.20
SCSCF_BIND_PORT=3870

# PCSCF
PCSCF_IP=172.22.0.21
PCSCF_BIND_PORT=3871

# SRSLTE ENB
SRS_ENB_IP=172.22.0.22

# UERANSIM
NR_GNB_IP=172.22.0.23
NR_UE_IP=172.22.0.24

UE1_IMEI=356938035643803
UE1_IMEISV=4370816125816151
UE1_IMSI=001011234567895
UE1_KI=8baf473f2f8fd09487cccbd7097c6862
UE1_OP=11111111111111111111111111111111
UE1_AMF=8000

# OAI ENB
OAI_ENB_IP=172.22.0.25

# OPEN5GS WEBUI
WEBUI_IP=172.22.0.26

# PCF
PCF_IP=172.22.0.27

# NSSF
NSSF_IP=172.22.0.28

# BSF
BSF_IP=172.22.0.29

# ENTITLEMENT SERVER
ENTITLEMENT_SERVER_IP=172.22.0.30

# OSMOMSC
OSMOMSC_IP=172.22.0.31

# OSMOHLR
OSMOHLR_IP=172.22.0.32

# SMSC
SMSC_IP=172.22.0.33

# SRSLTE UE
SRS_UE_IP=172.22.0.34

# SCP
SCP_IP=172.22.0.35

# METRICS
METRICS_IP=172.22.0.36

# SRSRAN GNB
SRS_GNB_IP=172.22.0.37

# GRAFANA
GRAFANA_IP=172.22.0.39

# UE IPv4 Subnet Range for APN=internet
UE_IPV4_INTERNET=192.168.100.0/24

# UE IPv4 Subnet Range for APN=ims
UE_IPV4_IMS=192.168.101.0/24

# Maximum Number of UEs
MAX_NUM_UE=1024
```

M2
```
# Set proper timezone to sync times between docker host and containers
#TZ=Europe/Berlin

MCC=001
MNC=01

TEST_NETWORK=172.22.0.0/24
DOCKER_HOST_IP=10.182.50.135

# MONGODB
MONGO_IP=172.22.0.2

# HSS - open5gs
HSS_IP=172.22.0.3

# PCRF
PCRF_IP=172.22.0.4
PCRF_BIND_PORT=3873

# SGW
SGWC_IP=172.22.0.5
SGWU_IP=172.22.0.6
SGWU_ADVERTISE_IP=172.22.0.6

# SMF
SMF_IP=172.22.0.7
SMF_DNS1=8.8.8.8
SMF_DNS2=8.8.4.4

# UPF
UPF_IP=172.22.0.8
UPF_ADVERTISE_IP=172.22.0.8

# MME
MME_IP=172.22.0.9

# AMF
AMF_IP=10.182.50.57

# AUSF
AUSF_IP=172.22.0.11

# NRF
NRF_IP=172.22.0.12

# UDM
UDM_IP=172.22.0.13

# UDR
UDR_IP=172.22.0.14

# IMS DNS
DNS_IP=172.22.0.15

# RTPENGINE
RTPENGINE_IP=172.22.0.16

# MYSQL
MYSQL_IP=172.22.0.17

# PYHSS
PYHSS_IP=172.22.0.18
PYHSS_BIND_PORT=3875

# ICSCF
ICSCF_IP=172.22.0.19
ICSCF_BIND_PORT=3869

# SCSCF
SCSCF_IP=172.22.0.20
SCSCF_BIND_PORT=3870

# PCSCF
PCSCF_IP=172.22.0.21
PCSCF_BIND_PORT=3871

# SRSLTE ENB
SRS_ENB_IP=172.22.0.22

# UERANSIM
NR_GNB_IP=172.22.0.23
NR_UE_IP=172.22.0.24

UE1_IMEI=356938035643803
UE1_IMEISV=4370816125816151
UE1_IMSI=001011234567895
UE1_KI=8baf473f2f8fd09487cccbd7097c6862
UE1_OP=11111111111111111111111111111111
UE1_AMF=8000

# OAI ENB
OAI_ENB_IP=172.22.0.25

# OPEN5GS WEBUI
WEBUI_IP=172.22.0.26

# PCF
PCF_IP=172.22.0.27

# NSSF
NSSF_IP=172.22.0.28

# BSF
BSF_IP=172.22.0.29

# ENTITLEMENT SERVER
ENTITLEMENT_SERVER_IP=172.22.0.30

# OSMOMSC
OSMOMSC_IP=172.22.0.31

# OSMOHLR
OSMOHLR_IP=172.22.0.32

# SMSC
SMSC_IP=172.22.0.33

# SRSLTE UE
SRS_UE_IP=172.22.0.34

# SCP
SCP_IP=172.22.0.35

# METRICS
METRICS_IP=172.22.0.36

# SRSRAN GNB
SRS_GNB_IP=10.182.50.135

# GRAFANA
GRAFANA_IP=172.22.0.39

# UE IPv4 Subnet Range for APN=internet
UE_IPV4_INTERNET=192.168.100.0/24

# UE IPv4 Subnet Range for APN=ims
UE_IPV4_IMS=192.168.101.0/24

# Maximum Number of UEs
MAX_NUM_UE=1024

```

M3
```
# Set proper timezone to sync times between docker host and containers
#TZ=Europe/Berlin

MCC=001
MNC=01

TEST_NETWORK=172.22.0.0/24
DOCKER_HOST_IP=10.182.50.32

# MONGODB
MONGO_IP=172.22.0.2

# HSS - open5gs
HSS_IP=172.22.0.3

SGWC_IP=172.22.0.5
SGWU_IP=172.22.0.6
SGWU_ADVERTISE_IP=172.22.0.6

# SMF
SMF_IP=172.22.0.7
SMF_DNS1=8.8.8.8
SMF_DNS2=8.8.4.4

# UPF
UPF_IP=172.22.0.8
UPF_ADVERTISE_IP=172.22.0.8

# MME
MME_IP=172.22.0.9

# AMF
AMF_IP=172.22.0.10

# AUSF
AUSF_IP=172.22.0.11

# NRF
NRF_IP=172.22.0.12

# UDM
UDM_IP=172.22.0.13

# UDR
UDR_IP=172.22.0.14

# IMS DNS
DNS_IP=172.22.0.15

# RTPENGINE
RTPENGINE_IP=172.22.0.16

# MYSQL
MYSQL_IP=172.22.0.17

# PYHSS
PYHSS_IP=172.22.0.18
PYHSS_BIND_PORT=3875

# ICSCF
ICSCF_IP=172.22.0.19
ICSCF_BIND_PORT=3869

# SCSCF
SCSCF_IP=172.22.0.20
SCSCF_BIND_PORT=3870

# PCSCF
PCSCF_IP=172.22.0.21
PCSCF_BIND_PORT=3871

# SRSLTE ENB
SRS_ENB_IP=172.22.0.22

# UERANSIM
NR_GNB_IP=172.22.0.23
NR_UE_IP=172.22.0.24

UE1_IMEI=356938035643803
UE1_IMEISV=4370816125816151
UE1_IMSI=001010999912301
UE1_KI=000102030405060708090a0b0c0d0e0f
UE1_OP=69d5c2eb2e2e624750541d3bbc692ba5
UE1_AMF=8000

# OAI ENB
OAI_ENB_IP=172.22.0.25

# OPEN5GS WEBUI
WEBUI_IP=172.22.0.26

# PCF
PCF_IP=172.22.0.27

# NSSF
NSSF_IP=172.22.0.28

# BSF
BSF_IP=172.22.0.29

# ENTITLEMENT SERVER
ENTITLEMENT_SERVER_IP=172.22.0.30

# OSMOMSC
OSMOMSC_IP=172.22.0.31

# OSMOHLR
OSMOHLR_IP=172.22.0.32

# SMSC
SMSC_IP=172.22.0.33

# SRSLTE UE
SRS_UE_IP=10.182.50.32

# SCP
SCP_IP=172.22.0.35

# METRICS
METRICS_IP=172.22.0.36

# SRSRAN GNB
SRS_GNB_IP=10.182.50.135

# GRAFANA
GRAFANA_IP=172.22.0.39

# UE IPv4 Subnet Range for APN=internet
UE_IPV4_INTERNET=192.168.100.0/24

# UE IPv4 Subnet Range for APN=ims
UE_IPV4_IMS=192.168.101.0/24

# Maximum Number of UEs
MAX_NUM_UE=1024

```

And, here are the config files.

M1 (sa-deploy.yaml)
```
version: '3'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    command: --bind_ip 0.0.0.0
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db
      - mongodbdata:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
  webui:
    image: docker_open5gs
    container_name: webui
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=webui
    volumes:
      - ./webui:/mnt/webui
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9999/tcp"
    ports:
      - "9999:9999/tcp"
    networks:
      default:
        ipv4_address: ${WEBUI_IP}
  nrf:
    image: docker_open5gs
    container_name: nrf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nrf-1
    volumes:
      - ./nrf:/mnt/nrf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${NRF_IP}
  scp:
    image: docker_open5gs
    container_name: scp
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=scp-1
    volumes:
      - ./scp:/mnt/scp
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${SCP_IP}
  ausf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
    container_name: ausf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ausf-1
    volumes:
      - ./ausf:/mnt/ausf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${AUSF_IP}
  udr:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: udr
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udr-1
    volumes:
      - ./udr:/mnt/udr
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${UDR_IP}
  udm:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
    container_name: udm
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udm-1
    volumes:
      - ./udm:/mnt/udm
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${UDM_IP}
  smf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - amf
    container_name: smf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smf-1
      - DEPLOY_MODE=5G
    volumes:
      - ./smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "9091/tcp"
    networks:
      default:
        ipv4_address: ${SMF_IP}
  upf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - smf
    container_name: upf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=upf-1
    volumes:
      - ./upf:/mnt/upf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
      - "9091/tcp"
    ports:
      - "2152:2152/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      #- net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        ipv4_address: ${UPF_IP}
  amf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - ausf
      - udm
      - udr
      - pcf
      - bsf
    container_name: amf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=amf-1
    volumes:
      - ./amf:/mnt/amf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "38412/sctp"
      - "7777/tcp"
      - "9091/tcp"
    ports:
      - "38412:38412/sctp"
    networks:
      default:
        ipv4_address: ${AMF_IP}
  pcf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: pcf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcf-1
    volumes:
      - ./pcf:/mnt/pcf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
      - "9091/tcp"
    networks:
      default:
        ipv4_address: ${PCF_IP}
  bsf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: bsf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=bsf-1
    volumes:
      - ./bsf:/mnt/bsf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${BSF_IP}
  nssf:
    image: docker_open5gs
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: nssf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nssf-1
    volumes:
      - ./nssf:/mnt/nssf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${NSSF_IP}
  metrics:
    build: ./metrics
    image: docker_metrics
    container_name: metrics
    env_file:
      - .env
    volumes:
      - ./metrics:/mnt/metrics
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9090/tcp"
    ports:
      - "9090:9090/tcp"
    networks:
      default:
        ipv4_address: ${METRICS_IP}
  grafana:
    build: ./grafana
    image: docker_grafana
    container_name: grafana
    env_file:
      - .env
    volumes:
      - ./grafana:/mnt/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000/tcp"
    ports:
      - "3000:3000/tcp"
    networks:
      default:
        ipv4_address: ${GRAFANA_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
volumes:
  mongodbdata: {}

```

M2 (srsgnb_zmq.yam;l)
```
version: '3'
services:
  srsgnb_zmq:
    image: docker_srsran
    container_name: srsgnb_zmq
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./srsran:/mnt/srsran
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=gnb_zmq
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "2000/tcp"
      - "2001/tcp"
    network_mode: host
#     networks:
#       default:
#         ipv4_address: ${SRS_GNB_IP}
# networks:
#   default:
#     external:
#       name: docker_open5gs_default

```

M3 (srsue_5g_zmq.yaml)
```
version: '3'
services:
  srsue_5g_zmq:
    image: docker_srslte
    container_name: srsue_5g_zmq
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue_5g_zmq
    expose:
      - "2000/tcp"
      - "2001/tcp"
    network_mode: host
#     networks:
#       default:
#         ipv4_address: ${SRS_UE_IP}
# networks:
#   default:
#     external:
#       name: docker_open5gs_default

```

When I run the ZMQ 5G UE, I can see tcp packets arriving on port 2000 on the GNB (M2) machine but the GNB cannot detect the UE which gets stuck at `Attaching UE...` message. 

Please note that I was able to run this setup on two machines earlier (5gcore on M1 and gnb+ue on M2). Any kind of help will be greatly appreciated!
