### DISCUSSION TITLE
Multiple PLMN with IMS

### DISCUSSION THREAD

**Discussion by ffxxcad** [herlesupreeth/docker_open5gs#393] [Q&A]
I am trying to set up multiple PLMNs using the sa-vonr-deploy.  My goal in doing this is to be eliminate the need for [reprogramming the SIM in order to connect an iPhone to a test network](https://github.com/herlesupreeth/docker_open5gs/discussions/248#discussioncomment-7392233) (001 01). I'd like the IMSI to be 00101XXX... but have the EHPLMN include a private PLMN (999 XX).  I added two new variables in the .env file:

```
MCC=999
MNC=XX

MCC2=001
MNC2=01
```
then adjusted the amf and nrf yaml files:

```
   guami:
      - plmn_id:
          mcc: MCC
          mnc: MNC
        amf_id:
          region: 2
          set: 1
      - plmn_id:
          mcc: MCC2
          mnc: MNC2
        amf_id:
          region: 5
          set: 2
    tai:
      - plmn_id:
          mcc: MCC
          mnc: MNC
        tac: 1
      - plmn_id:
          mcc: MCC2
          mnc: MNC2
          tac: 1
    plmn_support:
      - plmn_id:
          mcc: MCC
          mnc: MNC
        s_nssai:
          - sst: 1
      - plmn_id:
          mcc: MCC2
          mnc: MNC2
          s_nssai:
          - sst: 1
```
I also adjusted the EF.EHPLMN to include both PLMN (999 XX and 001 01) values.

The above configuration changes work with Open5GS but I am having difficulties getting all the IMS variables correctly configured.  I am curious if anyone else has tried using multiple PLMNs with IMS?

Thanks!
