### DISCUSSION TITLE
Connecting Quectel RM50N-GL to srsRAN and Open5GS

### DISCUSSION THREAD

**Discussion by mhafidi24** [herlesupreeth/docker_open5gs#448] [General]
Hi @herlesupreeth, I am using a Quectel RM520N-GL 5G module with Ubuntu 24.04.1 LTS as a UE. I am trying to connect it to srsRAN gNB and Open5GS, but it does not see my network. it only sees commercial networks such as (Telekom, Vodafone and o2).

This is probably not the right place for such a question but I am wondering if you managed to establish a successful connection with such a module to srsRAN gNB and Open5GS.

if yes, would be great if you can share some instructions on how to make it work.

Your help would be much appreciated!

Regards,
Mohamed

**Comment by herlesupreeth** [comment]
Yes, I have a Quectel RM520N-GL and it connects just fine.

You could use mmcli (ModemManager) in Ubuntu to manage that modem

For example:

```
sudo mmcli --help-3gpp
Usage:
  mmcli [OPTION…] - Control and monitor the ModemManager

3GPP options:
  --3gpp-scan                                                    Scan for available networks in a given modem.
  --3gpp-register-home                                           Request a given modem to register in its home network
  --3gpp-register-in-operator=[MCCMNC]                           Request a given modem to register in the network of the given operator
  --3gpp-set-eps-ue-mode-operation=[ps-1|ps-2|csps-1|csps-2]     Set the UE mode of operation for EPS
  --3gpp-set-initial-eps-bearer-settings=["key=value,..."]       Set the initial EPS bearer settings
  --3gpp-disable-facility-lock=[facility,key]                    Disable facility personalization
  --3gpp-set-packet-service-state=[attached|detached]            Set packet service state
  --3gpp-set-nr5g-registration-settings=["key=value,..."]        Set 5GNR registration settings
```

First list modem

`sudo mmcli -L`

then get the modem number from that list. Say its 0

then in order to scan for networks you could execute the following command

`sudo mmcli -m 0 --3gpp-scan`

or register to home network

`sudo mmcli -m 0 --3gpp-register-home`

**Reply by mhafidi24** [reply]
When I run the following commands, the modem only detects commercial networks during the scan:

`sudo mmcli -L`
/org/freedesktop/ModemManager1/Modem/2 [Quectel] RM520N-GL

`sudo mmcli -v -m 2 --3gpp-scan`

[07 Apr 2025, 16:35:57] [Debug] Forcing request to be run asynchronously
[07 Apr 2025, 16:35:57] [Debug] Assuming '2' is the modem index
[07 Apr 2025, 16:35:57] [Debug] ModemManager process found at ':1.431'
[07 Apr 2025, 16:35:57] [Debug] Modem found at '/org/freedesktop/ModemManager1/Modem/2'
[07 Apr 2025, 16:35:57] [Debug] Asynchronously scanning for networks...

  3GPP scan | networks: 
26203 - o2 - de (lte, available)
26202 - Vodafone (lte, available)
26201 - Telekom (lte, available)

I noticed that the modem is using the "ROW_Commercial" carrier config, and I'm wondering if this might be preventing it from registering with test networks like mine, which uses 00101 as the PLMN.

Do you have the same carrier config in your modem?

Thanks for your help!

**Reply by herlesupreeth** [reply]
If I remember correctly my modem is also using "ROW_Commercial" carrier config (also I didnt modify any such settings).

Here are couple of things you could investigate to get the modem working

1. Check the RAT types allowed (sudo mmcli -m <modem_number>)
2. If you are using USRP B210, then I would suggest using a GPSDO (atleast until UE attaches)

once GPSDO is connected set appropriate values for clock and sync in gNB configuration file

3. You could try reducing the channel BW (20Mhz) in srsRAN_Project gNb configuration file. Try setting gain value as follows if using B210

  tx_gain: 80                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                   # Receive gain of the RF might need to adjusted to the given situation.

4. If all of the above steps fail, then try using the AT command interface via minicom and refer to AT command manual 

sudo minicom --device /dev/ttyUSB3

**Reply by herlesupreeth** [reply]
This is what I get as output 

```
$ sudo mmcli -m 0
  -----------------------------------
  General  |                    path: /org/freedesktop/ModemManager1/Modem/0
           |               device id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  -----------------------------------
  Hardware |            manufacturer: Quectel
           |                   model: RM520N-GL
           |       firmware revision: RM520NGLAAR03A03M4G
           |          carrier config: ROW_Commercial
           | carrier config revision: 0A010809
           |            h/w revision: RM520N-GL
           |               supported: gsm-umts, lte, 5gnr
           |                 current: gsm-umts, lte, 5gnr
           |            equipment id: xxxxxxxxxxxxxxx
  -----------------------------------
  System   |                  device: /sys/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:08.0/0000:08:00.0/0000:09:0c.0/0000:0f:00.0/usb2/2-5
           |                 drivers: cdc_mbim, option
           |                  plugin: quectel
           |            primary port: cdc-wdm2
           |                   ports: cdc-wdm2 (mbim), ttyUSB1 (gps), ttyUSB2 (at), ttyUSB3 (at), 
           |                          wwan0 (net)
  -----------------------------------
  Status   |                   state: failed
           |           failed reason: sim-missing
           |             power state: on
  -----------------------------------
  Modes    |               supported: allowed: 3g; preferred: none
           |                          allowed: 4g; preferred: none
           |                          allowed: 3g, 4g; preferred: 4g
           |                          allowed: 3g, 4g; preferred: 3g
           |                          allowed: 5g; preferred: none
           |                          allowed: 4g, 5g; preferred: 5g
           |                          allowed: 4g, 5g; preferred: 4g
           |                          allowed: 3g, 5g; preferred: 5g
           |                          allowed: 3g, 5g; preferred: 3g
           |                          allowed: 3g, 4g, 5g; preferred: 5g
           |                          allowed: 3g, 4g, 5g; preferred: 4g
           |                          allowed: 3g, 4g, 5g; preferred: 3g
           |                 current: allowed: 3g, 4g, 5g; preferred: 5g
  -----------------------------------
  Bands    |               supported: utran-1, utran-4, utran-6, utran-5, utran-8, utran-2, 
           |                          eutran-1, eutran-2, eutran-3, eutran-4, eutran-5, eutran-7, eutran-8, 
           |                          eutran-12, eutran-13, eutran-14, eutran-17, eutran-18, eutran-19, 
           |                          eutran-20, eutran-25, eutran-26, eutran-28, eutran-29, eutran-30, 
           |                          eutran-32, eutran-34, eutran-38, eutran-39, eutran-40, eutran-41, 
           |                          eutran-42, eutran-43, eutran-46, eutran-48, eutran-66, eutran-71, 
           |                          utran-19, ngran-1, ngran-2, ngran-3, ngran-5, ngran-7, ngran-8, 
           |                          ngran-12, ngran-13, ngran-14, ngran-18, ngran-20, ngran-25, ngran-26, 
           |                          ngran-28, ngran-29, ngran-30, ngran-38, ngran-40, ngran-41, ngran-48, 
           |                          ngran-66, ngran-70, ngran-71, ngran-75, ngran-76, ngran-77, ngran-78, 
           |                          ngran-79
           |                 current: utran-1, utran-4, utran-5, utran-8, utran-2, eutran-1, 
           |                          eutran-2, eutran-3, eutran-4, eutran-5, eutran-7, eutran-8, 
           |                          eutran-12, eutran-13, eutran-14, eutran-17, eutran-18, eutran-19, 
           |                          eutran-20, eutran-25, eutran-26, eutran-28, eutran-29, eutran-30, 
           |                          eutran-32, eutran-34, eutran-38, eutran-39, eutran-40, eutran-41, 
           |                          eutran-42, eutran-43, eutran-46, eutran-48, eutran-66, eutran-71, 
           |                          utran-19, ngran-1, ngran-2, ngran-3, ngran-5, ngran-7, ngran-8, 
           |                          ngran-12, ngran-13, ngran-14, ngran-18, ngran-20, ngran-25, ngran-26, 
           |                          ngran-28, ngran-29, ngran-30, ngran-38, ngran-40, ngran-41, ngran-48, 
           |                          ngran-66, ngran-70, ngran-71, ngran-75, ngran-76, ngran-77, ngran-78, 
           |                          ngran-79
  -----------------------------------
  IP       |               supported: ipv4, ipv6, ipv4v6
  -----------------------------------
  SIM      |          sim slot paths: slot 1: none (active)
           |                          slot 2: none
```

**Comment by mhafidi24** [comment]
I'm using a USRP B210 with srsRAN gNB and the following configuration:
```

amf:
  addr: 192.168.178.81                                                 # The address or hostname of the AMF.
  bind_addr: 192.168.178.48                                          # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                              # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64    # Optionally pass arguments to the selected RF driver.
  clock: internal
  sync : internal
  srate: 23.04                                                    # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 80                                                     # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                     # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.

log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: info                                                 # Logging level applied to all layers. 

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

```
So the RF configuration matches your recommendations

regarding the RM520N modem I am facing an issue with mmcli, sometimes it shows a failed state with a sim-missing failure even though the SIM is inserted, this issue does not not show up when I use AT commands.


also, I noticed that the modem sees my network when I configure a PLMN different from 00101 such as 90170, but still does not register for some unknown reasons. it rarely sees my network with 00101 PLMN when I scan for networks using AT commands but also never registers.  the same SIM card works flawlessly in a OnePlus Nord2 5G, where it detects and registers to the test network with 00101 PLMN without any issues. in the other hand the OnePlus never sees 90170 PLMN.

```
mmcli -m 12
  -----------------------------------
  General  |                    path: /org/freedesktop/ModemManager1/Modem/12
           |               device id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  -----------------------------------
  Hardware |            manufacturer: Quectel
           |                   model: RM520N-GL
           |       firmware revision: RM520NGLAAR03A03M4G
           |          carrier config: ROW_Commercial
           | carrier config revision: 0A010809
           |            h/w revision: 20000
           |               supported: gsm-umts, lte, 5gnr
           |                 current: gsm-umts, lte, 5gnr
           |            equipment id: xxxxxxxxxxx
  -----------------------------------
  System   |                  device: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3
           |                 physdev: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3
           |                 drivers: option, qmi_wwan
           |                  plugin: quectel
           |            primary port: cdc-wdm0
           |                   ports: cdc-wdm0 (qmi), ttyUSB0 (ignored), ttyUSB1 (gps), 
           |                          ttyUSB2 (at), ttyUSB3 (at), wwan0 (net)
  -----------------------------------
  Status   |                   state: failed
           |           failed reason: sim-missing
           |             power state: on
  -----------------------------------
  Modes    |               supported: allowed: 3g; preferred: none
           |                          allowed: 4g; preferred: none
           |                          allowed: 3g, 4g; preferred: 4g
           |                          allowed: 3g, 4g; preferred: 3g
           |                          allowed: 5g; preferred: none
           |                          allowed: 4g, 5g; preferred: 5g
           |                          allowed: 4g, 5g; preferred: 4g
           |                          allowed: 3g, 5g; preferred: 5g
           |                          allowed: 3g, 5g; preferred: 3g
           |                          allowed: 3g, 4g, 5g; preferred: 5g
           |                          allowed: 3g, 4g, 5g; preferred: 4g
           |                          allowed: 3g, 4g, 5g; preferred: 3g
           |                 current: allowed: 5g; preferred: none
  -----------------------------------
  Bands    |               supported: utran-1, utran-4, utran-6, utran-5, utran-8, utran-2, 
           |                          eutran-1, eutran-2, eutran-3, eutran-4, eutran-5, eutran-7, eutran-8, 
           |                          eutran-12, eutran-13, eutran-14, eutran-17, eutran-18, eutran-19, 
           |                          eutran-20, eutran-25, eutran-26, eutran-28, eutran-29, eutran-30, 
           |                          eutran-32, eutran-34, eutran-38, eutran-39, eutran-40, eutran-41, 
           |                          eutran-42, eutran-43, eutran-46, eutran-48, eutran-66, eutran-71, 
           |                          utran-19, ngran-1, ngran-2, ngran-3, ngran-5, ngran-7, ngran-8, 
           |                          ngran-12, ngran-13, ngran-14, ngran-18, ngran-20, ngran-25, ngran-26, 
           |                          ngran-28, ngran-29, ngran-30, ngran-38, ngran-40, ngran-41, ngran-48, 
           |                          ngran-66, ngran-70, ngran-71, ngran-75, ngran-76, ngran-77, ngran-78, 
           |                          ngran-79
           |                 current: utran-1, utran-4, utran-5, utran-8, utran-2, eutran-1, 
           |                          eutran-2, eutran-3, eutran-4, eutran-5, eutran-7, eutran-8, 
           |                          eutran-12, eutran-13, eutran-14, eutran-17, eutran-18, eutran-19, 
           |                          eutran-20, eutran-25, eutran-26, eutran-28, eutran-29, eutran-30, 
           |                          eutran-32, eutran-34, eutran-38, eutran-39, eutran-40, eutran-41, 
           |                          eutran-42, eutran-43, eutran-46, eutran-48, eutran-66, eutran-71, 
           |                          utran-19, ngran-78
  -----------------------------------
  IP       |               supported: ipv4, ipv6, ipv4v6
  -----------------------------------
  3GPP     |                    imei: 868371054148057
  -----------------------------------
  SIM      |        primary sim path: /org/freedesktop/ModemManager1/SIM/5
           |          sim slot paths: slot 1: /org/freedesktop/ModemManager1/SIM/5 (active)
           |                          slot 2: none

```

Following are the used AT commands where the modem saw my network but couldn't register:

```
AT+CPIN?
+CPIN: READY

OK
AT+COPS=?
+COPS: (0,"vodafone.de","Vodafone","26202",7),(0,"o2 - de","o2 - de","26203",7),(0,"Test PLMN 1-1","Test1-1","00101",12),(0,"Telekom Deutschland GER","Telekom","26201",7),,(0-4),(0-2)

OK
AT+COPS=1,2,"00101",12
+CME ERROR: 13
```
