### ISSUE TITLE
Separate machines across different networks?

### ISSUE THREAD

**Issue by galalmounir** [herlesupreeth/docker_open5gs#231]
What is the best way to run the core dockers on one machine A on network A then run the ENB on a separate machine B on network B and have them communicate?

What I tried was putting Machine A's IP in `DOCKER_HOST_IP`, `SGWU_ADVERTISE_IP` and `UPF_ADVERTISE_IP`. 
I also uncommented the lines in the docker files. 
Finally, I port forwarded the two ports that are open in the docker files. 

The first issue I faced was being unable to run the srsenb.yaml docker-compose on Machine B, because the virtual docker network (external) is not available on that machine. I tried to manually create the virtual network. But was unable to get machine B (ENB) to connect to Machine A's core.

Any ideas?

**Comment by herlesupreeth** [comment]
Hey, if you are running eNB on an another machine then you would need to change the networking to host mode (rather than external) of srsenb.yaml docker-compose file so that there is no NATing done by the docker network.

i.e. remove the networks sections and add under srsenb section in that docker-compose file the following

`network_mode: host`

**Comment by galalmounir** [comment]
Thanks! 

I tried this and I got the following error:
```
srsenb    | bind(): Cannot assign requested address
srsenb    | Failed to bind on address 172.22.0.22, port 2152: Cannot assign requested address
srsenb    | Error initializing EUTRA stack.
```

This is what my srsenb.yaml looks like:
```
version: '3'
services:
  srsenb:
    image: galalhassan/docker_srslte
    container_name: srsenb
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - "/dev/bus"
    volumes:
      - /dev/serial:/dev/serial:ro
      - /dev/bus/usb:/dev/bus/usb:ro
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=enb
    expose:
      - "36412/sctp"
      - "2152/udp"
    network_mode: "host"
```
