### ISSUE TITLE
How to enable TLS?

### ISSUE THREAD

**Issue by cpyyyyyyyyy** [herlesupreeth/docker_open5gs#267]
I have modified nrf.yaml as follows, and then the NRF produces the following log `[sbi] INFO: nghttp2_server() [https://172.22.0.12]:7777`. I would like to know how to change the configuration of other NFs because currently, none of my NFs can register with the NRF. 
```
logger:
    file: /open5gs/install/var/log/open5gs/nrf.log

sbi:
    server:
      no_tls: false
      key: /open5gs/install/etc/open5gs/tls/nrf.key
      cert: /open5gs/install/etc/open5gs/tls/nrf.crt  
    client:
      no_tls: true

parameter:

nrf:
    sbi:
      - addr: NRF_IP
        port: 7777
```
Thank you!
