### ISSUE TITLE
Error response from daemon: invalid config for network docker_open5gs_default: invalid endpoint settings:

### ISSUE THREAD

**Issue by ajaydas03** [herlesupreeth/docker_open5gs#342]
Post running the "docker compose -f sa-deploy.yaml up" command getting the below error

Error response from daemon: invalid config for network docker_open5gs_default: invalid endpoint settings:

no configured subnet or ip-range contain the IP address 192.168.XX.XXX

please advise on it.

Thanks

**Comment by herlesupreeth** [comment]
Please post the docker-ce and docker compose version you are using and also any changes you made to the docker_open5gs code after cloning

**Comment by ajaydas03** [comment]
openshift@openshift:~$ sudo docker --version
Docker version 27.0.3, build 7d4bcd8
openshift@openshift:~$
openshift@openshift:~$ docker compose version
Docker Compose version v2.28.1
openshift@openshift:~$

i have not changed anything in code but i changed the IPs in following files srsgnb.yaml, sa-deploy.yaml for 
5G SA deployment. and made the necessary changes as per your given steps.

Kindly do let me know if you need more information.

Thanks

**Comment by herlesupreeth** [comment]
Please post the changes you did in srsgnb.yaml, sa-deploy.yaml.

**Comment by ajaydas03** [comment]
Hi,

Please find the attach.

[sa-deploy.txt](https://github.com/user-attachments/files/16423751/sa-deploy.txt)
[srsgnb.txt](https://github.com/user-attachments/files/16423755/srsgnb.txt)

**Comment by herlesupreeth** [comment]
why have you changed the below part ? please revert it

```
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.10.213/24
```

Also, there is some weird characters in srsgnb.yaml. Revert it if you are not sure what you are doing

```
        '''networks:
      default:
        ipv4_address: ${SRS_GNB_IP}'''
'''networks:
  default:
    external:
      name: docker_open5gs_default'''
```
