### ISSUE TITLE
SCTP issue during registration testing with UERANSIM

### ISSUE THREAD

**Issue by ajaydas03** [herlesupreeth/docker_open5gs#344]
Hi,

Can anyone help me with below issue ..i am getting this error while doing the "Registration" Testing with UERANSIM

root@f16fe841440e:/UERANSIM/build# ./nr-gnb -c /UERANSIM/config/open5gs-gnb.yaml
UERANSIM v3.2.6
[2024-08-02 13:48:27.258] [rls-udp] [error] RLS failure [Socket bind failed: Address already in use]
[2024-08-02 13:48:27.259] [sctp] [info] Trying to establish SCTP connection... (192.168.10.213:38412)
[2024-08-02 13:48:27.260] [gtp] [error] GTP/UDP task could not be created. Socket bind failed: Address already in use
[2024-08-02 13:48:27.276] [sctp] [info] **SCTP connection established (192.168.10.213:38412)**
[2024-08-02 13:48:27.277] [sctp] [debug] SCTP association setup ascId[276045]
[2024-08-02 13:48:27.277] [ngap] [debug] Sending NG Setup Request
[2024-08-02 13:48:27.309] [ngap] [debug] NG Setup Response received
[2024-08-02 13:48:27.309] [ngap] [info] NG Setup procedure is successful
[2024-08-02 13:48:30.985] [sctp] [warning] **Unhandled SCTP notification received**
[2024-08-02 13:48:32.009] [sctp] [warning] Unhandled SCTP notification received
^Croot@f16fe841440e:/UERANSIM/build# ^C

>>>> **changes in open5gs-gnb.yaml file are host ip and sd value.**

root@f16fe841440e:/UERANSIM/config# cat open5gs-gnb.yaml
```
mcc: '001'          # Mobile Country Code value
mnc: '01'          # Mobile Network Code value (2 or 3 digits)
 
nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code
 
linkIp: 172.22.0.23   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 172.22.0.23   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 172.22.0.23    # gNB's local IP address for N3 Interface (Usually same with local IP)
 
# List of AMF address information
amfConfigs:
  - address: **192.168.10.213**
    port: 38412
 
# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    **sd: 000001**
 
# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
```
root@f16fe841440e:/UERANSIM/config#
