### ISSUE TITLE
VONR radioNetwork: unspecified (0)

### ISSUE THREAD

**Issue by shuimoshusheng** [herlesupreeth/docker_open5gs#401]
Use the exp_5d_ims_pyhss branch and `ghcr.io/herlesupreath/docker_strsran ghcr.io/herlesupreeth/docker_srsran、ghcr.io/herlesupreeth/docker_open5gs、ghcr.io/herlesupreeth/docker_kamailio、ghcr.io/herlesupreeth/docker_rtpengine、ghcr.io/herlesupreeth/docker_pyhss 、ghcr.io/herlesupreeth/docker_mysql、ghcr.io/herlesupreeth/docker_metrics、ghcr.io/herlesupreeth/docker_dns、ghcr.io/herlesupreeth/docker_grafana、sa-vonr-deploy.yaml` Conduct a VONR test using Redmi Note 11t as the terminal, N2 access error, always released, prompting radioNetwork: unspecified (0)

**Comment by herlesupreeth** [comment]
First, the issue description is unreadable, please format it correctly. Second, if you dont upload any pcap file of the scenario you are testing nobody can help here.

**Comment by shuimoshusheng** [comment]
I use Docker images pulled from [packages,](https://github.com/herlesupreeth?tab=packages&repo_name=docker_open5gs)  git checkout to the exp_5d_ims_pyhss branch, and the image was launched using the sa-vonr-deployable. yaml configuration file, as shown below:
![image](https://github.com/user-attachments/assets/33a59867-e017-44b8-af77-4329df8f9265)
pyhss apn list:
`[
  {
    "apn_id": 1,
    "qci": 9,
    "nidd_scef_realm": null,
    "apn": "internet",
    "arp_priority": 4,
    "nidd_mechanism": null,
    "ip_version": 0,
    "arp_preemption_capability": false,
    "nidd_rds": null,
    "pgw_address": null,
    "arp_preemption_vulnerability": true,
    "nidd_preferred_data_mode": null,
    "sgw_address": null,
    "charging_rule_list": null,
    "last_modified": "2024-12-23T06:09:10Z",
    "charging_characteristics": "0800",
    "nbiot": false,
    "apn_ambr_dl": 0,
    "nidd_scef_id": null,
    "apn_ambr_ul": 0
  },
  {
    "apn_id": 2,
    "qci": 9,
    "nidd_scef_realm": null,
    "apn": "ims",
    "arp_priority": 4,
    "nidd_mechanism": null,
    "ip_version": 0,
    "arp_preemption_capability": false,
    "nidd_rds": null,
    "pgw_address": null,
    "arp_preemption_vulnerability": true,
    "nidd_preferred_data_mode": null,
    "sgw_address": null,
    "charging_rule_list": null,
    "last_modified": "2024-12-23T06:10:14Z",
    "charging_characteristics": "0800",
    "nbiot": false,
    "apn_ambr_dl": 0,
    "nidd_scef_id": null,
    "apn_ambr_ul": 0
  }
]`
auc list: `[
  {
    "amf": "8000",
    "lpa": null,
    "adm1": null,
    "sqn": 0,
    "pin1": null,
    "misc1": null,
    "iccid": null,
    "pin2": null,
    "misc2": null,
    "imsi": "466920000000001",
    "puk1": null,
    "misc3": null,
    "batch_name": null,
    "puk2": null,
    "misc4": null,
    "auc_id": 1,
    "sim_vendor": null,
    "kid": null,
    "last_modified": "2024-12-23T06:14:00Z",
    "ki": "00112233445566778899AABBCCDDEEFF",
    "esim": false,
    "psk": null,
    "opc": "000102030405060708090A0B0C0D0E0F",
    "des": null
  }
]`
subscriber list:
`[
  {
    "imsi": "466920000000001",
    "nam": 0,
    "serving_mme_peer": null,
    "enabled": true,
    "roaming_enabled": true,
    "last_modified": "2024-12-23T06:18:49Z",
    "auc_id": 1,
    "roaming_rule_list": null,
    "default_apn": 1,
    "subscribed_rau_tau_timer": 300,
    "apn_list": "1,2",
    "serving_mme": null,
    "msisdn": "8613312345670",
    "serving_mme_timestamp": null,
    "subscriber_id": 1,
    "ue_ambr_dl": 0,
    "serving_mme_realm": null,
    "ue_ambr_ul": 0
  }
]`
ims_subscriber '[
  {
    "ifc_path": "default_ifc.xml",
    "sh_profile": "string",
    "pcscf": null,
    "scscf": "sip:scscf.ims.mnc092.mcc466.3gppnetwork.org:6060",
    "pcscf_realm": null,
    "scscf_timestamp": null,
    "pcscf_active_session": null,
    "scscf_realm": "ims.mnc092.mcc466.3gppnetwork.org",
    "ims_subscriber_id": 1,
    "pcscf_timestamp": null,
    "scscf_peer": "scscf.ims.mnc092.mcc466.3gppnetwork.org",
    "msisdn": "8613312345670",
    "pcscf_peer": null,
    "sh_template_path": null,
    "last_modified": "2024-12-23T06:20:58Z",
    "msisdn_list": "[8613312345670]",
    "xcap_profile": null,
    "imsi": "466920000000001"
  }
]'
gnb use srsran_Project N78 with usrp b210 ,UE use redmi 11T pro, UE registration failed，N2 port packet capture shows no response to registration request. A release request was sent (reason for release: Cause: radioNetwork: unspecified (0)）， The captured file is as follows：

[N2-sbi.zip](https://github.com/user-attachments/files/18243046/N2-sbi.zip)

**Comment by shuimoshusheng** [comment]
> First, the issue description is unreadable, please format it correctly. Second, if you dont upload any pcap file of the scenario you are testing nobody can help here.

I use Docker images pulled from [packages,](https://github.com/herlesupreeth?tab=packages&repo_name=docker_open5gs)  git checkout to the exp_5d_ims_pyhss branch, and the image was launched using the sa-vonr-deployable. yaml configuration file, as shown below:

![docker ps](https://github.com/user-attachments/assets/9a135313-a693-462b-b54c-f4c0bf212243)


pyhss apn list: 
`
```json[
  {
    "apn_id": 1,
    "qci": 9,
    "nidd_scef_realm": null,
    "apn": "internet",
    "arp_priority": 4,
    "nidd_mechanism": null,
    "ip_version": 0,
    "arp_preemption_capability": false,
    "nidd_rds": null,
    "pgw_address": null,
    "arp_preemption_vulnerability": true,
    "nidd_preferred_data_mode": null,
    "sgw_address": null,
    "charging_rule_list": null,
    "last_modified": "2024-12-23T06:09:10Z",
    "charging_characteristics": "0800",
    "nbiot": false,
    "apn_ambr_dl": 0,
    "nidd_scef_id": null,
    "apn_ambr_ul": 0
  },
  {
    "apn_id": 2,
    "qci": 9,
    "nidd_scef_realm": null,
    "apn": "ims",
    "arp_priority": 4,
    "nidd_mechanism": null,
    "ip_version": 0,
    "arp_preemption_capability": false,
    "nidd_rds": null,
    "pgw_address": null,
    "arp_preemption_vulnerability": true,
    "nidd_preferred_data_mode": null,
    "sgw_address": null,
    "charging_rule_list": null,
    "last_modified": "2024-12-23T06:10:14Z",
    "charging_characteristics": "0800",
    "nbiot": false,
    "apn_ambr_dl": 0,
    "nidd_scef_id": null,
    "apn_ambr_ul": 0
  }
]```
`
auc list: 
```json[
  {
    "amf": "8000",
    "lpa": null,
    "adm1": null,
    "sqn": 0,
    "pin1": null,
    "misc1": null,
    "iccid": null,
    "pin2": null,
    "misc2": null,
    "imsi": "466920000000001",
    "puk1": null,
    "misc3": null,
    "batch_name": null,
    "puk2": null,
    "misc4": null,
    "auc_id": 1,
    "sim_vendor": null,
    "kid": null,
    "last_modified": "2024-12-23T06:14:00Z",
    "ki": "00112233445566778899AABBCCDDEEFF",
    "esim": false,
    "psk": null,
    "opc": "000102030405060708090A0B0C0D0E0F",
    "des": null
  }
]```

subscriber list:
`
```json[
  {
    "imsi": "466920000000001",
    "nam": 0,
    "serving_mme_peer": null,
    "enabled": true,
    "roaming_enabled": true,
    "last_modified": "2024-12-23T06:18:49Z",
    "auc_id": 1,
    "roaming_rule_list": null,
    "default_apn": 1,
    "subscribed_rau_tau_timer": 300,
    "apn_list": "1,2",
    "serving_mme": null,
    "msisdn": "8613312345670",
    "serving_mme_timestamp": null,
    "subscriber_id": 1,
    "ue_ambr_dl": 0,
    "serving_mme_realm": null,
    "ue_ambr_ul": 0
  }
]```
`
ims_subscriber:
`
````json[
  {
    "ifc_path": "default_ifc.xml",
    "sh_profile": "string",
    "pcscf": null,
    "scscf": "sip:scscf.ims.mnc092.mcc466.3gppnetwork.org:6060",
    "pcscf_realm": null,
    "scscf_timestamp": null,
    "pcscf_active_session": null,
    "scscf_realm": "ims.mnc092.mcc466.3gppnetwork.org",
    "ims_subscriber_id": 1,
    "pcscf_timestamp": null,
    "scscf_peer": "scscf.ims.mnc092.mcc466.3gppnetwork.org",
    "msisdn": "8613312345670",
    "pcscf_peer": null,
    "sh_template_path": null,
    "last_modified": "2024-12-23T06:20:58Z",
    "msisdn_list": "[8613312345670]",
    "xcap_profile": null,
    "imsi": "466920000000001"
  }
]```
`
gnb use srsran_Project N78 with usrp b210 ,UE use redmi 11T pro, UE registration failed，N2 port packet capture shows no response to registration request. A release request was sent (reason for release: Cause: radioNetwork: unspecified (0)）， The captured file is as follows：
[N2-sbi.zip](https://github.com/user-attachments/files/18243088/N2-sbi.zip)

**Comment by shuimoshusheng** [comment]
> First, the issue description is unreadable, please format it correctly. Second, if you dont upload any pcap file of the scenario you are testing nobody can help here.
I use Docker images pulled from [packages,](https://github.com/herlesupreeth?tab=packages&repo_name=docker_open5gs)  git checkout to the exp_5d_ims_pyhss branch, and the image was launched using the sa-vonr-deployable. yaml configuration file, as shown below:
![image](https://github.com/user-attachments/assets/4035cd84-822f-4fc4-90d3-9f1c35ec749c)


```json
pyhss apn list: [
  {
    "apn_id": 1,
    "qci": 9,
    "nidd_scef_realm": null,
    "apn": "internet",
    "arp_priority": 4,
    "nidd_mechanism": null,
    "ip_version": 0,
    "arp_preemption_capability": false,
    "nidd_rds": null,
    "pgw_address": null,
    "arp_preemption_vulnerability": true,
    "nidd_preferred_data_mode": null,
    "sgw_address": null,
    "charging_rule_list": null,
    "last_modified": "2024-12-23T06:09:10Z",
    "charging_characteristics": "0800",
    "nbiot": false,
    "apn_ambr_dl": 0,
    "nidd_scef_id": null,
    "apn_ambr_ul": 0
  },
  {
    "apn_id": 2,
    "qci": 9,
    "nidd_scef_realm": null,
    "apn": "ims",
    "arp_priority": 4,
    "nidd_mechanism": null,
    "ip_version": 0,
    "arp_preemption_capability": false,
    "nidd_rds": null,
    "pgw_address": null,
    "arp_preemption_vulnerability": true,
    "nidd_preferred_data_mode": null,
    "sgw_address": null,
    "charging_rule_list": null,
    "last_modified": "2024-12-23T06:10:14Z",
    "charging_characteristics": "0800",
    "nbiot": false,
    "apn_ambr_dl": 0,
    "nidd_scef_id": null,
    "apn_ambr_ul": 0
  }
]

auc list: 
[
  {
    "amf": "8000",
    "lpa": null,
    "adm1": null,
    "sqn": 0,
    "pin1": null,
    "misc1": null,
    "iccid": null,
    "pin2": null,
    "misc2": null,
    "imsi": "466920000000001",
    "puk1": null,
    "misc3": null,
    "batch_name": null,
    "puk2": null,
    "misc4": null,
    "auc_id": 1,
    "sim_vendor": null,
    "kid": null,
    "last_modified": "2024-12-23T06:14:00Z",
    "ki": "00112233445566778899AABBCCDDEEFF",
    "esim": false,
    "psk": null,
    "opc": "000102030405060708090A0B0C0D0E0F",
    "des": null
  }
]

subscriber list:
[
  {
    "imsi": "466920000000001",
    "nam": 0,
    "serving_mme_peer": null,
    "enabled": true,
    "roaming_enabled": true,
    "last_modified": "2024-12-23T06:18:49Z",
    "auc_id": 1,
    "roaming_rule_list": null,
    "default_apn": 1,
    "subscribed_rau_tau_timer": 300,
    "apn_list": "1,2",
    "serving_mme": null,
    "msisdn": "8613312345670",
    "serving_mme_timestamp": null,
    "subscriber_id": 1,
    "ue_ambr_dl": 0,
    "serving_mme_realm": null,
    "ue_ambr_ul": 0
  }
]

ims_subscriber:
[
  {
    "ifc_path": "default_ifc.xml",
    "sh_profile": "string",
    "pcscf": null,
    "scscf": "sip:scscf.ims.mnc092.mcc466.3gppnetwork.org:6060",
    "pcscf_realm": null,
    "scscf_timestamp": null,
    "pcscf_active_session": null,
    "scscf_realm": "ims.mnc092.mcc466.3gppnetwork.org",
    "ims_subscriber_id": 1,
    "pcscf_timestamp": null,
    "scscf_peer": "scscf.ims.mnc092.mcc466.3gppnetwork.org",
    "msisdn": "8613312345670",
    "pcscf_peer": null,
    "sh_template_path": null,
    "last_modified": "2024-12-23T06:20:58Z",
    "msisdn_list": "[8613312345670]",
    "xcap_profile": null,
    "imsi": "466920000000001"
  }
]

gnb use srsran_Project N78 with usrp b210 ,UE use redmi 11T pro, UE registration failed，N2 port packet capture shows no response to registration request. A release request was sent (reason for release: Cause: radioNetwork: unspecified (0)）， The captured file is as follows：

[N2-sbi.zip](https://github.com/user-attachments/files/18243099/N2-sbi.zip)

**Comment by shuimoshusheng** [comment]
> First, the issue description is unreadable, please format it correctly. Second, if you dont upload any pcap file of the scenario you are testing nobody can help here.

I use Docker images pulled from packages, Git, however, was replaced with the exp_5d_ims_pyhss branch, and the image was launched using the sa-vonr-deployable. yaml configuration file, as shown below:
![image](https://github.com/user-attachments/assets/e8343e85-c302-4222-9d01-5f51983828b4)

Gnb use srsRAN_project with B210， UE use redmi note 11T，N2 port packet capture shows no response to registration request. A release request was sent (reason for release: Cause: radioNetwork: unspecified (0)）， The captured file is as follows: 
[N2-sbi.zip](https://github.com/user-attachments/files/18243119/N2-sbi.zip)


```json
{
  "pyhss_data": {
    "apn_list": [
      {
        "apn_id": 1,
        "qci": 9,
        "nidd_scef_realm": null,
        "apn": "internet",
        "arp_priority": 4,
        "nidd_mechanism": null,
        "ip_version": 0,
        "arp_preemption_capability": false,
        "nidd_rds": null,
        "pgw_address": null,
        "arp_preemption_vulnerability": true,
        "nidd_preferred_data_mode": null,
        "sgw_address": null,
        "charging_rule_list": null,
        "last_modified": "2024-12-23T06:09:10Z",
        "charging_characteristics": "0800",
        "nbiot": false,
        "apn_ambr_dl": 0,
        "nidd_scef_id": null,
        "apn_ambr_ul": 0
      },
      {
        "apn_id": 2,
        "qci": 9,
        "nidd_scef_realm": null,
        "apn": "ims",
        "arp_priority": 4,
        "nidd_mechanism": null,
        "ip_version": 0,
        "arp_preemption_capability": false,
        "nidd_rds": null,
        "pgw_address": null,
        "arp_preemption_vulnerability": true,
        "nidd_preferred_data_mode": null,
        "sgw_address": null,
        "charging_rule_list": null,
        "last_modified": "2024-12-23T06:10:14Z",
        "charging_characteristics": "0800",
        "nbiot": false,
        "apn_ambr_dl": 0,
        "nidd_scef_id": null,
        "apn_ambr_ul": 0
      }
    ],
    "auc_list": [
      {
        "amf": "8000",
        "lpa": null,
        "adm1": null,
        "sqn": 0,
        "pin1": null,
        "misc1": null,
        "iccid": null,
        "pin2": null,
        "misc2": null,
        "imsi": "466920000000001",
        "puk1": null,
        "misc3": null,
        "batch_name": null,
        "puk2": null,
        "misc4": null,
        "auc_id": 1,
        "sim_vendor": null,
        "kid": null,
        "last_modified": "2024-12-23T06:14:00Z",
        "ki": "00112233445566778899AABBCCDDEEFF",
        "esim": false,
        "psk": null,
        "opc": "000102030405060708090A0B0C0D0E0F",
        "des": null
      }
    ],
    "subscriber_list": [
      {
        "imsi": "466920000000001",
        "nam": 0,
        "serving_mme_peer": null,
        "enabled": true,
        "roaming_enabled": true,
        "last_modified": "2024-12-23T06:18:49Z",
        "auc_id": 1,
        "roaming_rule_list": null,
        "default_apn": 1,
        "subscribed_rau_tau_timer": 300,
        "apn_list": "1,2",
        "serving_mme": null,
        "msisdn": "8613312345670",
        "serving_mme_timestamp": null,
        "subscriber_id": 1,
        "ue_ambr_dl": 0,
        "serving_mme_realm": null,
        "ue_ambr_ul": 0
      }
    ],
    "ims_subscriber_list": [
      {
        "ifc_path": "default_ifc.xml",
        "sh_profile": "string",
        "pcscf": null,
        "scscf": "sip:scscf.ims.mnc092.mcc466.3gppnetwork.org:6060",
        "pcscf_realm": null,
        "scscf_timestamp": null,
        "pcscf_active_session": null,
        "scscf_realm": "ims.mnc092.mcc466.3gppnetwork.org",
        "ims_subscriber_id": 1,
        "pcscf_timestamp": null,
        "scscf_peer": "scscf.ims.mnc092.mcc466.3gppnetwork.org",
        "msisdn": "8613312345670",
        "pcscf_peer": null,
        "sh_template_path": null,
        "last_modified": "2024-12-23T06:20:58Z",
        "msisdn_list": "[8613312345670]",
        "xcap_profile": null,
        "imsi": "466920000000001"
      }
    ]
  }
}

**Comment by herlesupreeth** [comment]
Looks like a setup issue on your gNB. I would rather raise this issue in srsRAN_Project after having a look at your configuration files

**Comment by shuimoshusheng** [comment]
> Looks like a setup issue on your gNB. I would rather raise this issue in srsRAN_Project after having a look at your configuration files

gnb config:

```
cu_cp:
  amf:
    addr: 172.17.32.63
    #addr: 172.17.32.100
    port: 38412
    bind_addr: 172.17.32.74
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "46692"
            tai_slice_support_list:
              - sst: 1
ru_sdr:
  device_driver: uhd
  device_args: type=b200,serial=190933,num_recv_frames=64,num_send_frames=64
  clock: gpsdo
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 641280
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "46692"
  tac: 1
  pci: 1

log:
  filename: /tmp/gnb.log
  all_level: warning

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
```
qos config:

```
qos:
  -
    five_qi: 1 # E.g. Conversational Voice
    pdcp:
      tx:
        sn: 12
        discard_timer: -1
        status_report_required: false
      rx:
        sn: 12
        t_reordering: 80
        out_of_order_delivery: false
    f1u_cu_up:
      backoff_timer: 10
    f1u_du:
      backoff_timer: 10
    rlc:
      mode: um-bidir
      um-bidir:
        tx:
          sn: 12
          queue-size: 16384
          queue-bytes: 6172672
        rx:
          sn: 12
          t-reassembly: 50
  -
    five_qi: 2 # E.g. Conversational Video
    pdcp:
      tx:
        sn: 12
        discard_timer: -1
        status_report_required: false
      rx:
        sn: 12
        t_reordering: 80
        out_of_order_delivery: false
    f1u_cu_up:
      backoff_timer: 10
    f1u_du:
      backoff_timer: 10
    rlc:
      mode: um-bidir
      um-bidir:
        tx:
          sn: 12
          queue-size: 16384
          queue-bytes: 6172672
        rx:
          sn: 12
          t-reassembly: 50
  -
    five_qi: 5 # E.g. IMS signaling
    rlc:
      mode: am
      am:
        tx:
          sn: 12
          t-poll-retransmit: 80
          max-retx-threshold: 4
          poll-pdu: 64
          poll-byte: 125
          queue-size: 16384
          queue-bytes: 6172672
        rx:
          sn: 12
          t-reassembly: 80
          t-status-prohibit: 10
    pdcp:
      integrity_required: false
      tx:
        sn: 12
        discard_timer: -1
        status_report_required: false
      rx:
        sn: 12
        t_reordering: 80
        out_of_order_delivery: false
    f1u_du:
      backoff_timer: 10
    f1u_cu_up:
      backoff_timer: 10
  -
    five_qi: 7 # E.g. Voice, Video (live streaming)
    pdcp:
      integrity_required: false
      tx:
        sn: 12
        discard_timer: -1
        status_report_required: false
      rx:
        sn: 12
        t_reordering: 80
        out_of_order_delivery: false
    f1u_cu_up:
      backoff_timer: 10
    f1u_du:
      backoff_timer: 10
    rlc:
      mode: um-bidir
      um-bidir:
        tx:
          sn: 12
          queue-size: 16384
          queue-bytes: 6172672
        rx:
          sn: 12
          t-reassembly: 100
  -
    five_qi: 9 # E.g. Buffered video streaming, TCP-based traffic
    pdcp:
      tx:
        sn: 18
        discard_timer: -1
        status_report_required: false
      rx:
        sn: 18
        t_reordering: 220
        out_of_order_delivery: false
    f1u_cu_up:
      backoff_timer: 10
    f1u_du:
      backoff_timer: 10
    rlc:
      mode: am
      am:
        tx:
          sn: 18
          t-poll-retransmit: 20
          max-retx-threshold: 32
          poll-pdu: 16
          poll-byte: -1
          queue-size: 16384
          queue-bytes: 6172672
        rx:
          sn: 18
          t-reassembly: 20
          t-status-prohibit: 10
```
