### ISSUE TITLE
About adding "expose: 2152/udp" in the smf section of docker-compose.yaml

### ISSUE THREAD

**Issue by s5uishida** [herlesupreeth/docker_open5gs#87]
Hi @herlesupreeth 

According to the following Open5GS Quickstart figure,

https://open5gs.org/open5gs/docs/guide/01-quickstart/

It seems good to add the `expose` of the N4u(Sxu)`2152/udp` in `smf` section of `docker-compose.yaml`.

```
  smf:
    image: docker_open5gs
    container_name: smf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smf-1
    volumes:
      - ./smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
+     - "2152/udp"
      - "8805/udp"
      - "2123/udp"
    networks:
      default:
        ipv4_address: ${SMF_IP}
```
I'm sorry if I made a mistake. (Even without this setting, it worked fine until now)

Best regards,

--Shigeru
