### ISSUE TITLE
UE failed to ping UPF after separating RAN and 5GC

### ISSUE THREAD

**Issue by ljysdfz** [herlesupreeth/docker_open5gs#88]
@herlesupreeth
 
Hello, Herle and every other lovely guy.
I have tried to externalize ueransim and deploy it in a separate VM that resides outside the 5GC SA networks.
ueransim part was left as much the way as it used to be.
My version of open5gs is v2.4.7, ueransim version is v3.2.6.
This is the specific topology:
![image](https://user-images.githubusercontent.com/3489980/172274072-585182d4-4a92-41bd-8dd2-1e9df4a6e230.png)

Both of the gNB and UE were up, but I found that the UE failed to ping `192.168.100.1`, that is the data plane of UPF.

![image](https://user-images.githubusercontent.com/3489980/172114769-3b881a5d-27ef-498e-9e0f-232f0045c5b2.png)

gNB log:
![gnb_bridge](https://user-images.githubusercontent.com/3489980/172114500-92037d62-18c3-4144-85d2-c8e64c86d460.png)

ip route table in gNB
![image](https://user-images.githubusercontent.com/3489980/172115044-0ab47d3e-54fb-438d-8e0f-7a20c6202c90.png)

NIC list in gNB
![image](https://user-images.githubusercontent.com/3489980/172115100-8028aac5-e31a-4fd3-b28d-a16ce2c7f914.png)

UE log:
![ue_bridge](https://user-images.githubusercontent.com/3489980/172114544-0126933d-865e-42f7-8dbf-eb50b73bcd43.png)

ip route table in UE
![image](https://user-images.githubusercontent.com/3489980/172114911-d0ec44a7-ccec-4c9b-a1c1-9d33b5a1cad9.png)

NIC list in UE
![image](https://user-images.githubusercontent.com/3489980/172114990-a7d51d10-2f0c-49b4-af96-752cadf08af1.png)

What's weird was that UE was able to ping `192.168.100.1` through the NIC `eth0`.

![image](https://user-images.githubusercontent.com/3489980/172117436-feb9d149-1884-4052-ab8d-ce1b2323f882.png)

And if you look at the proper examples in the integrated version set up before, you can find that the name of eth0 should be `eth0@uesimtun0` instead of `eth0@if14`. In that way, the traffic enters eth0 will finally pass through the GTP-U tunnel.

the proper one:
![image](https://user-images.githubusercontent.com/3489980/172119061-15d049c1-206e-41fb-894e-71367bee9090.png)

From here, I will show what have been configured in the VMs.
I've done these things in the VM-5GC, aka 5GC SA networks:
1. In the `.env` file, change `UPF_ADVERTISE_IP` -> `DOCKER_HOST_IP`
2. In the `sa-deploy.yaml` file, uncomment these 2 code blocks in order to enforce port mappings.
```
    # ports:
    #   - "38412:38412/sctp"
```
```
    # ports:
    #   - "2152:2152/udp"
```

I've made a new folder `ran/` for the individual RAN.
Here is a breakdown of the file system.
```
ran/
  gnb/
    Dockerfile
    open5gs-gnb.yaml
  ue/
    Dockerfile
    open5gs-ue.yaml
  nr-gnb.yaml
  nr-ue.yaml
```

I will list a series of aforementioned configuration out here:

ran/gnb/Dockerfile
```
# These are some built images used as prerequisites
FROM docker_ueransim:builder AS ueransim_builder
FROM docker_ueransim:ueransim_provenance

# I just put every single environmental constants in place, 
# then extract the original shell codes and put them into a static Dockerfile
COPY --from=ueransim_builder /UERANSIM/build/nr-gnb /ueransim/nr-gnb
COPY open5gs-gnb.yaml /ueransim
WORKDIR /ueransim
CMD     export IP_ADDR=$(awk 'END{print $1}' /etc/hosts) && \
        ./nr-gnb -c open5gs-gnb.yaml & bash
```

ran/gnb/open5gs-gnb.yaml
```
......
......
linkIp: 172.23.0.2  # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 172.23.0.2   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 172.23.0.2   # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 192.168.12.6
    port: 38412
......
......
```

ran/ue/Dockerfile
```
FROM docker_ueransim:builder AS ueransim_builder
FROM docker_ueransim:ueransim_provenance

COPY --from=ueransim_builder /UERANSIM/build/nr-ue /ueransim/nr-ue
COPY open5gs-ue.yaml /ueransim
WORKDIR /ueransim
CMD     export IP_ADDR=$(awk 'END{print $1}' /etc/hosts) && \
        ./nr-ue -c open5gs-ue.yaml & bash
```

ran/ue/open5gs-ue.yaml
```
......
......
# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 172.23.0.2
......
......
```

ran/nr-gnb.yaml
```
version: '3'
services:
  nr_gnb:
    image: docker_ueransim_gnb
    container_name: nr_gnb
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    privileged: true
    networks:
      default:
        ipv4_address: 172.23.0.2
networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
```

ran/nr-ue.yaml
```
version: '3'
services:
  nr_ue:
    image: docker_ueransim_ue
    container_name: nr_ue
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: 172.23.0.3
networks:
  default:
    name: ran_default
```

In light of the fact that there is only ONE IP allocated per VM, so that there is no more host IP space for a `vlan` (ipvlan or macvlan) driver, though I've made it through by using a `ipvlan` for the target scenario. I have to use the `bridge` driver to save IP addresses.
I hope whoever is looking at this would come up with a favorable advice or solution. Thank you in advance.
